version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_container
    environment:
      POSTGRES_DB: db_usuario
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"

